# tasks file for rh-osp-demo-prereqs/metallb
- name: "[METALLB] Create metallb namespace"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: metallb-system

- name: "[METALLB] Create metallb operator group"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: metallb-operator
        namespace: metallb-system

- name: "[METALLB] Create metallb operator"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: metallb-operator-sub
        namespace: metallb-system
      spec:
        channel: stable
        name: metallb-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: "[METALLB] Wait and confirm status for metallb operator"
  ansible.builtin.command: 
    cmd: 'oc get clusterserviceversion -n metallb-system  -o custom-columns=Name:.metadata.name,Phase:.status.phase'
  register: output
  until: '(output.stdout_lines | length > 1) and "Succeeded" in output.stdout_lines[1]'
  retries: 40
  delay: 2

- name: "[METALLB] Create metallb instance resource"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: MetalLB
      metadata:
        name: metallb
        namespace: metallb-system
      spec:
        nodeSelector:
          node-role.kubernetes.io/worker: ""

- name: "[METALLB] Wait and confirm status for metallb instance resource"
  ansible.builtin.command: 
    cmd: 'oc get deployment openshift-apiserver-operator -n openshift-apiserver-operator -o custom-columns=Available:.status.availableReplicas'
  register: output
  until: '(output.stdout_lines | length > 1) and "1" in output.stdout_lines[1]'
  retries: 40
  delay: 2

- name: "[METALLB] Wait and confirm status for metallb daemonset speaker"
  ansible.builtin.command: 
    cmd: 'oc get daemonset -n metallb-system speaker -o custom-columns=test:.status.numberReady'
  register: output
  until: '(output.stdout_lines | length > 1) and "3" in output.stdout_lines[1]'
  retries: 40
  delay: 2
