---
# tasks file for rhoso-ng-attach
- name: "[Net Attach] Attach pods to the ctlplane network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: ctlplane
        namespace: openstack
      spec:
        config: |
          {
            "cniVersion": "0.3.1",
            "name": "ctlplane",
            "type": "macvlan",
            "master": "enp1s0",
            "ipam": {
              "type": "whereabouts",
              "range": "172.22.0.0/24",
              "range_start": "172.22.0.30",
              "range_end": "172.22.0.70"
            }
          }

- name: "[Net Attach] Attach pods to the ctlplane network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: internalapi
        namespace: openstack
      spec:
        config: |
          {
            "cniVersion": "0.3.1",
            "name": "internalapi",
            "type": "macvlan",
            "master": "enp1s0.20", 
            "ipam": { 
              "type": "whereabouts", 
              "range": "172.17.0.0/24",
              "range_start": "172.17.0.30", 
              "range_end": "172.17.0.70"
            }
          }

- name: "[Net Attach] Attach pods to the storage network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: storage
        namespace: openstack
      spec:
        config: |
          {
            "cniVersion": "0.3.1",
            "name": "storage",
            "type": "macvlan",
            "master": "enp1s0.21", 
            "ipam": {
              "type": "whereabouts",
              "range": "172.18.0.0/24",
              "range_start": "172.18.0.30",
              "range_end": "172.18.0.70"
            }
          }

- name: "[Net Attach] Attach pods to the tenant network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: tenant
        namespace: openstack
      spec:
        config: |
          {
            "cniVersion": "0.3.1",
            "name": "tenant",
            "type": "macvlan",
            "master": "enp1s0.22",
            "ipam": {
              "type": "whereabouts",
              "range": "172.19.0.0/24",
              "range_start": "172.19.0.30",
              "range_end": "172.19.0.70"
            }
          }

- name: "[Net Attach] Attach pods to the external network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: external
        namespace: openstack
      spec:
        config: |
          {
            "cniVersion": "0.3.1",
            "name": "external",
            "type": "macvlan",
            "master": "enp3s0",
            "ipam": {
              "type": "whereabouts",
              "range": "192.168.123.0/24",
              "range_start": "192.168.123.60",
              "range_end": "192.168.123.110"
              }
            }
