---
# tasks file for rhoso-ng-lb-ip-address-pools
- name: "[LB IP Addr Pool] ctlplane ip address pool network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        namespace: metallb-system
        name: ctlplane
      spec:
        addresses:
        - 172.22.0.80-172.22.0.90
  tags: rhoso-ip-addr-pools

- name: "[LB IP Addr Pool] interalapi ip address pool network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        namespace: metallb-system
        name: internalapi
      spec:
        addresses:
        - 172.17.0.80-172.17.0.90
  tags: rhoso-ip-addr-pools

- name: "[LB IP Addr Pool] storage ip address pool network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        namespace: metallb-system
        name: storage
      spec:
        addresses:
        - 172.18.0.80-172.18.0.90
  tags: rhoso-ip-addr-pools

- name: "[LB IP Addr Pool] tenant ip address pool network"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        namespace: metallb-system
        name: tenant
      spec:
        addresses:
        - 172.19.0.80-172.19.0.90
  tags: rhoso-ip-addr-pools
