- name: "[ControlPlane Secret] Create RHOSO LibVirt Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: libvirt-secret
        namespace: openstack
      type: Opaque
      data:
        LibvirtPassword: b3BlbnN0YWNr
  tags: rhoso-control-plane-deploy
