---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  clusterDomain: apps.kf8xz.dynamic.redhatworkshops.io
  localClusterDomain: apps.kf8xz.dynamic.redhatworkshops.io
main:
  clusterGroupName: openstack-on-openshift
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
