- name: "[OPENSTACK OPERATOR] Creating openstack-operators namespace" 
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openstack-operators
  tags: openstack-operator-deploy

- name: "[OPENSTACK OPERATOR] Creating openstack-operators namespace" 
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openstack
  tags: openstack-operator-deploy

- name: "[OPENSTACK OPERATOR] Creating operator group for openstack operator"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: openstack
        namespace: openstack-operators
  tags: openstack-operator-deploy

- name: "[OPENSTACK OPERATOR] Install openstack operator"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/openstack-operator.openstack-operators: ""
        name: openstack-operator
        namespace: openstack-operators
      spec:
        channel: stable-v1.0
        installPlanApproval: Automatic
        name: openstack-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
  tags: openstack-operator-deploy
 
- name: "[OPENSTACK OPERATOR] Wait and confirm status for openstack operator"
  ansible.builtin.shell:
    cmd: "oc get operators openstack-operator.openstack-operators -o json | jq '.status.components.labelSelector.matchExpressions[].operator'"
  register: output
  until: '"Exists" in output.stdout_lines[0]'
  retries: 40
  delay: 4
  tags: openstack-operator-deploy

